name: R
channels:
  - conda-forge
dependencies:
  - r-base=4.4.1
  - r-tidyverse
  - r-devtools
  - r-rmarkdown
  - r-knitr
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-bayesplot
  - pip
  - pip:
    - jupyter
